# Generated by Django 4.2 on 2023-04-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=150)),
                ('short_url_key', models.CharField(max_length=7)),
            ],
        ),
    ]
