# Generated by Django 4.2 on 2023-04-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_url_key',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
